#!/bin/bash
set -e

cd $(dirname $0)

if [[ "$1" == "" ]]; then
	../phpunit $1 --bootstrap ./src/stub.php --test-suffix '_test.php,-test.php,Test.php,.phpt' tests
else
	../phpunit --bootstrap ./src/stub.php $1
fi
